/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://qjwzyreda5gt7bgkjte4dd4guy.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://qav7uzc66e.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:7601c6b6-815e-4d2e-a444-1b436a0edd76",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_A4OSijYmx",
    "aws_user_pools_web_client_id": "5vvinfkf5odpcepsk4anlafo1l",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_user_files_s3_bucket": "apidentalapp144c9e5836ff40878c8dda1a9249b54a185021-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
